junehee/삼총사.js
junehee/숫자문자열과영단어.js
junehee/최소직사각형.js

Level 0 으로 오타났는데 그냥 진행시켜봅니다. (당당)

230608(목) 알고리즘 스터디

---

dongmin/크레인 인형뽑기 게임.js

[PGM] 크레인 인형뽑기 게임 / Level 1 / 60분+

---

dongmin/키패드 누르기.js

[PGM] 키패드 누르기 / Level 1 / 45분

---

키패드 누르기(이전 풀이).js

[PGM] 키패드 누르기(이전 풀이) / Level 1 / 60분+

---

Kled/키패드 누르기.js

타겟 넘버가 가운데 열에 해당하는 경우의 조건문에서
`centralNumbers.indexOf(number)`를 반복해서 코딩했는데
하나의 변수에 저장하면 코드 중복을 줄일 수 있을 것 같아서 이 점이 아쉬웠습니다!

[PGM] 키패드 누르기 / Level 1 / 60분

---

dongmin/바탕화면 정리.js

문제가 길어서 식겁했는데 다행히 생각한대로 바로 풀렸습니다!

[PGM] 바탕화면 정리 / Level 1 / 7분

---

Kled/바탕화면 정리.js

다행히 문제는 크게 어렵지 않았으나,
문제를 읽고 주어진 테스트 케이스를 이해하는데만 10분이 넘게 걸렸습니다. 😅😅😅

[PGM] 바탕화면 정리 / Level 1 / 15분

---

Kled/달리기 경주.js

처음에는 해시 하나로 풀려고 했다가 시간 초과 등으로 헤매다가
해시와 배열을 동시에 운영하여 풀었습니다.

[PGM] 달리기 경주 / Level 1 / 60분

---

dongmin/신고 결과 받기.js

`new Set()` 을 사용하다가 이상하게 꼬여서 그냥 안쓰고 풀었습니다 ㅎㅎ...

[PGM] 신고 결과 받기 / Level 1 / 40분

---

Kled/최댓값과 최솟값.js

[PGM] 최댓값과 최솟값 / Level 2 / 1분

---

Kled/JadenCase 문자열 만들기.js

이전 문제가 다소 쉬웠다보니 해당 문제도 꼼꼼히 문제를 읽지 않았다가 헤맸습니다.
추가적으로 구조분해를 사용하고 싶었는데 문법이 생각이 안나서 아쉬웠습니다. 😅

[PGM] JadenCase 문자열 만들기 / Level 2 / 20분

---

Kled/최솟값 만들기.js

A 배열은 오름차순 정렬,
B 배열은 내림차순 정렬 후 같은 인덱스 요소끼리 곱의 합을 구했습니다.

[PGM] 최솟값 만들기 / Level 2 / 3분

---

dongmin/올바른 괄호.js

첨에 아래처럼 했다가 효율성 테스트에서 걸려서 수정했습니다 ㅜㅜ
```javascript
function solution(s) {
let count = 0;
for (i = 0; i < s.length; i += 1) {
s.charAt(i) === '(' ? (count += 1) : (count -= 1);
if (count < 0) {
return false;
}
}
return count ? false : true;
}
```

[PGM] 올바른 괄호 / Level 2 / 15분

---

Kled/이진 변환 반복하기.js

[PGM] 이진 변환 반복하기 / Level 2 / 30분

---

dongmin/숫자의 표현.js

연속된 자연수의 가장 큰 수가 a라고 했을 때
자연수가 1 개면 -> `a`
자연수가 2 개면 -> `a + (a - 1)` = `2a - 1`
자연수가 3 개면 -> `a + (a - 1) + (a - 2)` = `3a - (1 + 2)`
자연수가 4 개면 -> `a + (a - 1) + (a - 2) + (a - 3)` = `4a - (1 + 2 + 3)`
즉, 자연수가 i 개면 -> `ia - (1 + 2 + 3 + ... + (i - 1))`
이걸 이용해서 무식하게 `for`문을 돌렸습니다 ㅎㅎ...

[PGM] 숫자의 표현 / Level 2 / 20분

---

Kled/숫자의 표현.js

시간 복잡도가 관건인 문제였습니다!
첫 번째 `for문`의 시간 복잡도를 반으로 줄여서 해결했습니다.

[PGM] 숫자의 표현 / Level 2 / 8분

---

Kled/피보나치 수.js

테스트 케이스 7번부터 오버플로가 나길래 도움을 살짝 구했습니다. 나머지 연산이 이런 규칙이 있었군요.

[PGM] 피보나치 수 / Level 2 / 20분

---

Kled/짝지어 제거하기.js

최초에는 아래와 같이 `Array.from`을 통한 배열 순회를 진행했으나, 효율성에서 통과하지 못하는 문제가 있었습니다.
`[...string].forEach()`와 `Array.from()` 모두 시간 복잡도는 O(n)일텐데 효율성은 전개 구문을 통한 배열화 이후 순회가 더 빨랐습니다.
```js
function solution(s) {
let stack = [];
Array.from(s, value => {
if (stack[stack.length - 1] === value) {
return stack.pop()
}
stack.push(value)
})
return stack.length ? 0 : 1;
}
```

[PGM] 짝지어 제거하기 / Level 2 / 10분

---

Kled/영어 끝말잇기.js

[PGM] 영어 끝말잇기 / Level 2 / 40분

---

dongmin/카펫.js

`x * y = brown + yellow`
`(x-2) * (y-2) = yellow`
이 두 식을 이용해서 풀었습니다!

[PGM] 카펫 / Level 2 / 25분

---

dongmin/구명보트.js

무거운 사람을 기준으로 계산해야 한다는건 금방 떠올렸는데 코드로 구현하는데 한참 걸렸습니다 ㅜㅜ

[PGM] 구명보트 / Level 2 / 40분

---

junehee/구명보트.js
junehee/점프와순간이동.js
junehee/키패드누르기.js

점프와 순간이동 어려울 거 같아서 구명보트 먼저 풀었는데
구명보트 후에 다시 풀어보니 생각보다 쉽더라고요!
구명보트는 sort 후에 처리가 필요한 거 같았는데
limit 관련해서 조건을 어떻게 걸어야 할지 감이 안와서 한참 걸렸습니다 😂

[PGM] 구명보트, 점프와 순간 이동 / Level 2 / 50분, 30분

---

Kled/구명보트.js
Kled/점프와 순간 이동.js

최초에는 시간 복잡도를 줄이기 위해, 주어진 거리의 절반까지만 구하려는 퍼포먼스를 하다가 시간이 오래걸렸읍니다.
(주어진 거리의 절반까지 이동하고 그 뒤에는 순간 이동으로 도착)
가장 가벼운 사람과, limit에 딱 알맞는 파트너를 구하려다가 오래 걸렸습니다.
(lightman, limit - lightman)

[PGM] 점프와 순간 이동, 구명보트 / Level 2 / 30분, 60분

---

junehee/N개의최소공배수.js

매개변수로 주어진 arr를 reduce로 돌면서 최소공배수를 구해야하는 거까지는 접근했는데
최소공배수 로직에서 애먹었네요. reduce 안에서 해결해보려고 했는데 도저히 안돼서 서치의 도움을 살짝 받았습니다. 🫠
최소공배수 최대공약수는,, 외우는 것으로,,

[PGM] N개의 최소공배수 / Level 2 / 1시간 이상

---

junehee/최솟값만들기.js

N개의 최소공배수 풀다가 머리가 터져서 🤯
잠시 연어가 되어.. 패스했던 앞 부분 거슬러 다녀왔습니다.

[PGM] 최솟값 만들기 / Level 2 / 5분

---

dongmin/N개의 최소공배수.js

다 풀고 다른 답안 보니 완전 수학적으로 접근해서 `reduce()`랑 재귀로 푸는 방법이 있던데 나중에 외워뒀다가 잘 써먹어도 될 것 같습니다!

[PGM] N개의 최소공배수 / Level 2 / 20분

---

Kled/N개의 최소공배수.js
Kled/예상 대진표.js

`while`의 조건문을 어떻게 빨리 구해내는 지가 시간 단축의 중점이었던 것 같습니다.
최초에는 모든 요소들을 곱하고, 2씩 나눠가면서 최소 공배수를 찾았는데, 올바른 접근법이 아닌 것 같아
가장 큰 요소를 기준점 삼아 늘려가며 최소 공배수를 찾을 수 있었습니다.

[PGM] 예상 대진표, N개의 최소공배수 / Level 2 / 20분, 25분

---

Kled/멀리 뛰기.js

6칸 멀리 뛰기까지 직접 계산해보니 피보나치의 향기가 진하게 났읍니다.

[PGM] 멀리 뛰기 / Level 2 / 30분

---

dongmin/멀리 뛰기.js

[PGM] 멀리 뛰기 / Level 2 / 15분

---

junehee/멀리뛰기.js

쉬울줄 알고 혼자 삽질하다가 피보나치라는 것을 깨달아버리고..
피보나치도 연어하고 오겠습니다 😵‍💫

[PGM] 멀리뛰기 / Level 2 / 1시간

---

Kled/귤 고르기.js

[PGM] 귤 고르기 / Level 2 / 15분

---

Kled/괄호 회전하기.js
Kled/연속 부분 수열 합의 개수.js

연속된 배열을 어떻게 구현해야하나 마땅한 방법을 생각하지 못해서 많이 시간을 소모했습니다.

[PGM] 연속 부분 수열 합의 개수, 괄호 회전하기 / Level 2 / 60분+, 50분

---

dongmin/귤 고르기.js

[PGM] 귤 고르기 / Level 2 / 20분

---

dongmin/괄호 회전하기.js

처음엔 이렇게 풀었는데 `[ ( ] )` 와 같은 반례를 넘기지 못해서 새로 푸느라 오래 걸렸습니다...
```javascript
function solution(s) {
let count = 0;
let smallBracket = 0,
middleBracket = 0,
largeBracket = 0;
// 각 문자마다 카운트를 변경시키는 함수 할당
const brackets = {
'(' : () => { smallBracket += 1 },
')' : () => { smallBracket -= 1 },
'{' : () => { middleBracket += 1 },
'}' : () => { middleBracket -= 1 },
'[' : () => { largeBracket += 1 },
']' : () => { largeBracket -= 1 }
};
for (let i = 0; i < s.length; i += 1) {
let correct = true;
for (let j = 0; j < s.length; j += 1) {
// 즉시 실행 함수로 카운트 변경
brackets[s[j]]();
// 하나라도 음수가 되면(닫힌 괄호가 먼저 나오면) 문자열 검증 종료
if (smallBracket < 0 || middleBracket < 0 || largeBracket < 0) {
correct = false;
break;
}
}
if (correct) {
count += 1;
}
const [first, ...rest] = s;
s = [...rest, first].join(''); …
```

[PGM] 괄호 회전하기 / Level 2 / 60분+

---

dongmin/할인 행사.js

중간에 `hash`를 구성하는 대신 `filter()` 를 썼으면 조금 더 간결해질 수 있었을 것 같습니다 ㅎㅎ

[PGM] 할인 행사 / Level 2 / 35분

---

dongmin/n^2 배열 자르기.js

총 3번의 시도가 있었고 두 번째 까지는 효율성에서 걸리거나 테스트케이스를 모두 통과하지 못했습니다.
결과적으로 사용한 방법은 '`left`부터 `right`까지만 x좌표와 y좌표 검증하기' 였습니다!
예를 들어 `n = 5` 라면
`[1, 2, 3, 4, 5]` `[2, 2, 3, 4, 5]` `[3, 3, 3, 4, 5]` `[4. 4. 4. 4. 5]` `[5, 5, 5, 5, 5]`
이렇게 배열이 구성되게 됩니다.
이때, 규칙을 살펴보면
즉, 총 25개의 수중 `i`번째 수를 찾는다면 `i - 1`을 `n`인 5로 나눈 몫이 배열의 위치인 `x`가 되고, 해당 배열 내에서의 인덱스인 `y`는 `i - 1`을 `n`인 5로 나눈 나머지가 됩니다.
`y`가 `x`와 같거나 작은 경우의 `y`번째 요소는 모두 `x`이고, 그 외의 경우의 `y`번째 요소는 모두 `y` 입니다. 
```javascript
let str = '';
for (let i = 1; i <= n; i += 1) {
for (let j = 1; j <= n; j += 1) {
str += Math.max(i, j);
}
}
const cuttedStr = str.slice(left, right + 1);
return Array.from(cuttedStr, (numStr) => Number(numStr));
```
```javascript
let str = '';
const getX = (index) => Math.trunc((index - 1) / n);
const getY = (index) => (index - 1) % n; …
```

[PGM] n^2 배열 자르기 / Level 2 / 60분+

---

Kled/[1차] 캐시.js

캐시 교체 알고리즘 `LRU`에 대해서 처음 알았고, 테스트코드 풀이가 없다보니 많이 당황했던 문제였지만
캐시 개념이 있으시다면 어렵지 않게 풀이하실 수 있으실 것 같습니다.

[PGM] [1차] 캐시 / Level 2 /  30분

---

Kled/의상.js

이전 해시 카테고리의 문제를 풀 때 경험했던 문제라 수월하게 풀었습니다.

[PGM] 의상 / Level 2 / 10분

---

Kled/n^2 배열 자르기.js
Kled/할인 행사.js

최초에는 `discount` 할인 내역의 요소가 `want`에 포함되지 않을 수도 있다는 가정을 고려하지 않았습니다.
그리고 객체의 얕은 복사로 인해 원본 배열이 의도와 달리 변경되는 점 때문에 오래 걸렸던 것 같습니다.
<br />
최초 테스트케이스 2개는 15분만에 통과했지만 역시나 효율성을 요구하는 문제였던 것 같습니다.
시작점과 끝점을 어떻게 찾는 지가 관건이었던 것 같습니다.

[PGM] 할인 행사, n^2 배열 자르기 / Level 2 / 60분+, 50분

---

dongmin/캐시.js

이미 캐시에 포함된 도시에 대한 처리를 안했다가 삽질 좀 했습니다 ㅜㅜ

[PGM] 캐시 / Level 2 / 25분

---

dongmin/의상.js

해당 카테고리를 고르지 않는 경우를 빼먹어서 조금 헤맸습니다...!
그리고 해쉬를 생성하는 과정에서
희태님이 지난번에 쓰셨던 `setter` 내부에서 조건문을 취하는 방법과
준희님의 `( hash[el] || 0 ) + 1` 조건문을 적절히 섞어서 써봤습니다!
```javascript
map.set(category, (map.get(category) || 0) + 1);
```

[PGM] 의상 / Level 2 / 20분

---

dongmin/튜플.js

`string`으로 된 괄호들을 처리하는게 문제였습니다...

[PGM] 튜플 / Level 2 / 15분

---

Kled/H-Index.js

깜빡하고 안올렸었네요 반성합니다. 칼같은 리뷰로 혼내주십쇼

[PGM] H-Index / Level 2 / 20분

---

Kled/튜플.js

```js
"{{2},{2,1},{2,1,3},{2,1,3,4}}"
```
이차원 객체. 근데 문자열을 곁들인..
형변환 과정에서 잦은 삽질로 인해 너무 오래걸렸습니다

[PGM] 튜플 / Level 2 / 40분

---

Kled/기능개발.js

`if - else`를 안쓰고 분기 처리를 하고 싶었지만 이루어내지 못해서 아쉬웠습니다.

[PGM] 기능개발 / Level 2 / 30분

---

dongmin/H-index.js

[PGM] H-index / Level 2 / 15분

---

dongmin/행렬의 곱셈.js

처음에 `for`문을 2개만 썼다가 뭔가 이상해서 뜯어 고치느라 시간이 더 지체됐습니다... 행렬을 배열로 놓으니까 인지부조화 장난 아니네요

[PGM] 행렬의 곱셈 / Level 2 / 30분

---

dongmin/기능개발.js

배포가 지연되는 작업을 골라내는 부분이 자꾸 꼬여서 오래걸렸습니다 ㅜㅜ

[PGM] 기능개발 / Level 2 / 50분

---

프로세스.js

문제에서 주어진 예시처럼 해당 우선순위에 대한 별칭을 인덱스로 달아줬습니다!
다만 `indexArray` 배열을 `let`으로 선언해 매번 재할당 하는게 좋은 방법인지 잘 모르겠습니다

[PGM] 프로세스 / Level 2 / 15분

---

dongmin/뉴스 클러스터링.js

총 3시간 가량 걸렸습니다... 영문자만 할당해야 한다는 부분을 간과해서 시간을 정말 많이 썼고
중복 요소에 대한 합집합을 어떻게 구할까 하다가 교집합과 차집합으로 합집합을 구하는 아이디어가 떠올라 풀 수 있었습니다!
그리고 추가로 알파벳인지 구분하는 다른 방법에는 무엇이 있을까 하고 찾아보니 아스키 코드를 이용하는 방법이 있었습니다
아스키코드의 `65 ~ 90` 번은 소문자, `97 ~ 122`번은 대문자라고 하네요!
```javascript
const isAlphabet = (string) => {
const code = string.charCodeAt(0);
return (code >= 97 && code <= 122) || (code >= 65 && code <= 90);
};
```

[PGM] 뉴스 클러스터링 / Level 2 / 60분+

---

피로도.js

`DFS` 정석 문제는 처음 풀어봐서 너무 어렵고 이해하는데 한참 걸렸습니다 ㅜㅜ 힌트도 보고 검색도 해보다가 결국 정답 보고 제 방식으로 한번 코드로 옮겨봤습니다!

[PGM] 피로도 / Level 2 / 60분+

---

Kled/프로세스.js

주제는 스택 문제이지만 스택에 맞게 풀지 않았던 것 같아 아쉽습니다. 또한 변수를 너무 많이 선언한 점도 아쉽습니다

[PGM] 프로세스 / Level 2 / 60분

---

Kled/전화번호 목록.js

시간 복잡도의 지옥에 빠졌었는데, 도대체 어떻게 단일 반복문으로 처리할 수 있을까 고민하던 찰나,
구현하고자 하는 `sort()`를 통한 배열 정렬이 숫자가 아닌 문자열 비교임을 너무나도 늦게 알아버렸습니다..
근데 왜 해시 문제인지 궁금하네요 알려주실 동민님 구합니다

[PGM] 전화번호 목록 / Level 2 / 60분+

---

dongmin/전화번호 목록.js

예전에는 다른 사람의 힌트에서 본 `startsWith` 라는 접두사 구분 메서드를 가지고 풀었었는데 이번엔 새로운 방법으로 풀어봤습니다!
```javascript
function solution(phone_book) {
phone_book.sort();
for (let i = 0; i < phone_book.length - 1; i += 1) {
if (phone_book[i + 1].startsWith(phone_book[i])) {
return false;
}
}
return true;
}
```

[PGM] 전화번호 목록 / Level 2 / 20분

---

dongmin/압축.js

문제 이해를 제대로 안하고 들어간 부분도 있고 로직 구성을 어떻게 해야할지 고민하는데 쓴 시간이 엄청 많았습니다...

[PGM] 압축 / Level 2 / 60분+

---

dongmin/모음사전.js

[PGM] 모음사전 / Level 2 / 35분

---

dongmin/n진수 게임.js

[PGM] n진수 게임 / Level 2 / 20분

---

Kled/k진수에서 소수 개수 구하기.js

소수 판별 함수 만드는데 30분, 아래 조건식 만들면서 삽질하다가 결국 오버했습니다 ㅠ_ㅠ
```
- 0P0처럼 소수 양쪽에 0이 있는 경우
- P0처럼 소수 오른쪽에만 0이 있고 왼쪽에는 아무것도 없는 경우
- 0P처럼 소수 왼쪽에만 0이 있고 오른쪽에는 아무것도 없는 경우
- P처럼 소수 양쪽에 아무것도 없는 경우
```

[PGM] k진수에서 소수 개수 구하기 / Level 2 / 60분+

---

Kled/[3차] 압축.js

[PGM] [3차] 압축 / Level 2 / 60분

---

Kled/[3차] n진수 게임.js

`while` 내 로직 구현에서 시간을 좀 소모했습니다.
내 인덱스가 `n진수`로 변환한 string의 length보다 클 경우, 다음 숫자를 변환 후 덧붙여서 길이를 계속 보완합니다.

[PGM] [3차] n진수 게임 / Level 2 / 40분

---

junehee/올바른괄호.js

오늘 문제들이 너무 어려워서 윗문제 풀고 왔습니다.
while, for ~ of, 삼항연산자 등등 모두 효율성 미통과 되었습니다 ,,
효율성 따지기는 너무 어렵네요. 시간복잡도 개념을 잘 알아두어야겠어요 ㅠㅠ

[PGM] 올바른 괄호 / Level 2 / 30분

---

dongmin/주차 요금 계산.js

[PGM] 주차 요금 계산 / Level 2 / 35분

---

dongmin/뒤에 있는 큰 수 찾기.js

히든테케 마지막 4개에서 시간초과를 보고나서 해결을 못하고 결국 정답을 봤습니다 ㅜㅜ
```javascript
function solution(numbers) {
const answer = [];
numbers.forEach((num, idx) => {
if (idx === numbers.length - 1) {
answer.push(-1);
}
for (let i = idx + 1; i < numbers.length; i += 1) {
if (numbers[i] > num) {
answer.push(numbers[i]);
break;
}
if (numbers.length - 1 === i) {
answer.push(-1);
}
}
});
return answer;
}
```

[PGM] 뒤에 있는 큰 수 찾기 / Level 2 / 실패

---

Kled/주식가격.js

일단 문제를 이해하는데만 10분이 걸렸던 것 같아요. 만나봤던 지문 중에 가독성 최악이었습니다. 😅
이후 해시를 이용해서 푸려고 했으나, key가 고유하지 않아서 1차로 헤매고, 시간 복잡도에 2차로 헤맸던 것 같습니다..

[PGM] 주식가격 / Level 2 / 60분

---

Kled/주차 요금 계산.js

시간 복잡도 문제는 아닌 것 같고, 빡구현 문제인 것 같은데.. 
이게 맞나.. 를 반복하며 너무 오래걸렸네요 ㅠ_ㅠ

[PGM] 주차 요금 계산 / Level 2 / 60분+

---

Kled/방문 길이.js

좌표만 보고 무지성 BFS로 처음에 접근했다가 런타임 에러가 뜨더군요..
BFS인척 하는 문제이지 않았나.. 싶습니다.
풀이도 엉성하지만 문제를 잘 읽고 해석하는 것도 능력인 것 같네요

[PGM] 방문 길이 / Level 2 / 40분

---

junehee/푸드파이트대회.js

기존 문자열 풀이 방식에서 배열 방식으로 다시 풀어봤습니다!

[PGM] 푸드 파이트 대회 / Level 1 / 20분

---

dongmin/주식가격.js

반복문을 중첩했는데 효율성에서 안걸려서 다행입니다 ㅎㅎ

[PGM] 주식가격 / Level 2 / 15분

---

dongmin/방문 길이.js

조건을 계속 덧대다보니 덕지덕지 누더기코드가 되어버렸습니다
그리고 다 풀고 나서 생각해보니 코드의 가장 마지막에서  `new Set()` 으로 중복된 좌표를 제거했다면 더 깔끔하게 풀 수 있었을 것 같네요!
추가로 마지막 경로 길이 합산 과정에 `Map.prototype.values()`와 `Array.from()`을 사용했다면 더 좋았을 것 같습니다!
```javascript
function solution(dirs) {
let x = 0;
let y = 0;
const visited = new Map();
for (let i = 0; i < dirs.length; i += 1) {
// Up
if (dirs[i] === "U" && y <= 4) {
y += 1;
visited.set(x, [...(visited.get(x) || []), y - 0.5]);
continue;
}
// Down
if (dirs[i] === "D" && y >= -4) {
y -= 1;
visited.set(x, [...(visited.get(x) || []), y + 0.5]);
continue;
}
// Right
if (dirs[i] === "R" && x <= 4) {
x += 1;
visited.set(x - 0.5, [...(visited.get(x - 0.5) || []), y]);
continue;
}
// Left
if (dirs[i] === "L" && x >= -4) {
x -= 1;
visited.set(x + 0.5, [...(visited.get(x + 0.5) || []), y]); …
```

[PGM] 방문 길이 / Level 2 / 50분

---

dongmin/오픈채팅방.js

[PGM]오픈채팅방 / Level 2 / 20분

---

Kled/스킬트리.js

[PGM] 스킬트리 / Level 2 / 15분

---

Kled/[3차] 파일명 정렬.js

`parseInt(string, 10)`을 이용해서, 10진수 radix 문자열 이외의 문자열은 무시한다는 것이 중요했던 것 같습니다!

[PGM] [3차] 파일명 정렬 / Level 2 / 50분

---

junehee/모의고사.js

30분이면 선방했습니다.
왜냐하면 지난 번에 풀다 포기한 문제이기 때문이죠
내일 소수 만들기가 두렵다............😰

[PGM] 모의고사 / Level 1 / 30분

---

junehee/기사단원의무기.js

실수로 병합 전에 브랜치가 클로즈되어서 다시 올립니다!

[PGM] 기사단원의 무기 / Level 1 / 1시간 +@

---

howoo/소수만들기.js

[PGM] 소수 만들기 / Level 1 / 30분

---

소수찾기.js

소수 만들기 풀고난 뒤 푸니까 훨씬 이해가 잘 되네요
반복 학습의 중요성...bb
(브랜치 실수로 소수 만들기 PR 못올리고 바로 병합됐습니다 허허허;)

[PGM] 소수 찾기 / Level 1 / 30분

---

기사단원의무기, 소수찾기.js

[PGM] 기사단원의 무기, 소수찾기 / Level 1 / 빠른포기

---

junehee/덧칠하기.js

처음에 아래와 같이 접근했었는데 다 실패하고 ㅠㅠ 방향을 조금 바꿔서 다시 풀어봤습니다.
그리고 다른 사람 풀이 찾아보니 for...of 통해서 간단하게 구현했길래 따라해봤어요!
- 오답들
```javascript
function solution(n, m, section) {
// 페인트칠 최소 횟수
let answer = 0;
// wall = 모두 칠해져 있다는 가정이 된 배열
// forEach() 통해 section을 false 처리
let wall = new Array(n).fill(true);
section.forEach(v => wall[v-1] = false);
for (let i = 0; i < wall.length; i++) {
if (wall[i]) continue;
for (let j = i; j < wall.length; j+=m) {
wall[j] = true
}
answer++;
}
return answer;
}
```
```javascript
function solution(n, m, section) {
// 페인트칠 최소 횟수
let answer = 0
let wall = new Array(n).fill(false);
section.forEach(v => wall[v-1] = true)
while (wall.includes(true)) {
let i = 0
wall.splice(i, m, "")
i += m;
answer++;
return answer;
}
```

[PGM] 덧칠 하기 / Level 1 / 50분

---

junehee/실패율.js

오랜만에 다시 푸니까 시간은 짧아졌는데 여전히 어렵네요 ^_ㅠ

[PGM] 실패율 / Level 1 / 30분

---

junehee/옹알이(2).js

드디어 풀었지만.....
공백 치환 부분이 이해가 안 가서 서치의 도움을 조금 받았습니다 🥲

[PGM] 옹알이 (2) / Level 1 / 2시간

---

junehee/로또의최고순위와최저순위.js

작년에 한 번 풀었던 건데 다시 풀어봤어요
옹알이 다트게임보다는 풀만한 느낌입니다(?)

[PGM] 로또의 최고 순위와 최저 순위 / Level 1 / 30분

---

junehee/문자열나누기.js

지난 번에는 배열로 담아서 풀었었는데
아무래도 주어진 기본 형식이 숫자로 카운팅 하도록 되어있는 문제였다보니
그 방식으로 다시 바꿔서 풀어봤습니다!
문자열이 남았을 경우 카운팅 하는 걸 까먹어서 ㅋㅋㅋ 마지막에 count++ 해주니 통과됐네요

[PGM] 문자열 나누기 / Level 1 / 30분

---

howoo/로또의 최고 순위와 최저 순위.js
howoo/문자열 나누기.js

[PGM] 문자열 나누기 / level1 / 20분

---

junehee/숫자짝꿍.js

무려 for문 4개!
최적화도 해봤는데 저는 메서드보다 for문이 눈에 더 잘 들어오는 편이라
처음 풀었던 풀이로 올려봅니다.

[PGM] 숫자 짝꿍 / Level 1 / 1시간

---

junehee/완주하지못한선수.js

예전에 한번 풀었던 거라 다시 풀고 또 유명한 map 풀이를 공부해봤는데 어렵네요...
다음 주부턴 이제 안 풀어본 문제들이라 2시간씩 걸리 거 같습니돠. 허허.

[PGM] 완주하지 못한 선수 / Level 1 / 30분

---

junehee/둘만의암호.js

skip에 포함됐을 때 그냥 건너뛰라는 줄 알았는데 카운트를 건너뛰는 거였네요
이거 놓쳐서 잠시 삽질 했습니다 🥲

[PGM] 둘만의 암호 / Level 1 / 40분

---

howoo/완주하지 못한 선수.js

[PGM] 완주하지 못한 선수 / level 1 / 60++

---

dongmin/파일명 정렬.js

`isNaN()`이 공백을 인지하지 못한다는 사실을 깨닫기까지 너무 오랜 시간이 걸렸습니다..........................................

[PGM] 파일명 정렬 / Level 2 / 60분+

---

dongmin/타겟 넘버.js

[PGM] 타겟 넘버 / Level 2 / 15분

---

dongmin/게임 맵 최단거리.js

처음에 아래 코드로 짰다가 테케는 모두 통과했는데 효율성 테스트를 하나도 통과하지 못했습니다...
```javascript
function solution(maps) {
const mapsY = maps.length - 1;
const mapsX = maps[0].length - 1;
const queue = [[0, 0, 1]];
const visited = Array.from({ length: mapsY + 1 }, (_, idx) => [...maps[idx]]);
while (queue.length > 0) {
const current = queue.shift();
const [y, x, answer] = current;
visited[y][x] = 0;
if (y === mapsY && x === mapsX) {
return answer;
}
// 왼쪽
if (x - 1 >= 0 && visited[y][x - 1]) {
queue.push([y, x - 1, answer + 1]);
}
// 오른쪽
if (x + 1 <= mapsX && visited[y][x + 1]) {
queue.push([y, x + 1, answer + 1]);
}
// 위
if (y - 1 >= 0 && visited[y - 1][x]) {
queue.push([y - 1, x, answer + 1]);
}
// 아래
if (y + 1 <= mapsY && visited[y + 1][x]) {
queue.push([y + 1, x, answer + 1]);
}
}
return -1;
}
```

[PGM] 게임 맵 최단거리 / Level 2 / 60분+

---

junehee/바탕화면정리.js

[PGM] 바탕화면 정리 / Level 1 / 1시간 +@

---

junehee/최댓값과최솟값.js

위에 있는 방법으로 먼저 풀었던 건데
문자열 두번 돌면서 전개 연산자 사용하는게 마음에 안 들어서
한 번 소팅하고 제일 앞/제일 뒤 요소 사용하는 방안으로 바꿔보았습니다!

[PGM] 최댓값과 최솟값 / Level 2 / 5분

---

howoo/제이든케이스 문자열 만들기.js
howoo/키패드누르기.js

[pgm] / 제이든케이스 문자열 만들기 / level1 / 30분

---

junehee/최솟값만들기.js

이전 풀이에서 안 쓰던 변수 삭제하고 reduce 풀이로 다시 도전해봤습니다!
reduce에서 idx 값을 거의 안 썻었는데 꽤나 유용하네요!

[PGM] 최솟값 만들기 / Level 2 / 20분

---

junehee/올바른괄호.js

며칠 전 알고리즘 책에서 비슷한 내용 공부했던 기억이 있어서 스택으로 다시 풀어봤어요!
한 번에 풀진 못했는데 재밌네요!!

[PGM] 올바른 괄호 / Level 2 / 20분

---

junehee/숫자의표현.js

[PGM] 숫자의 표현 / Level 2 / 30분

---

howoo/구명보트.js

[PGM] 구명보트 / LEVEL2 / 못품

---

junehee/구명보트.js

지난 번에 한 번 풀었던 거라 쉽게 풀었네요! ㅋㅋ
곧 알고리즘 책에서도 하겠지만 최댓값 최솟값 구하는 그리디도 꼭 알아둬야 할 거 같아요

[PGM] 구명보트 / Level 2 / 10분

---

junehee/N개의최소공배수.js

작년에 풀었던 건데도 다시 풀고 이해하는데 한참 걸렸네요 ^.^...;;
1부터 시작하던 최소공배수를 두 수 중에 큰 거 부터 시작하도록 수정했습니다.

[PGM] N개의 최소공배수 / Level 2 / 1시간+@

---

howoo/멀리뛰기.js

재귀로 푸니깐 시간초과 나더라고요.
메모이제이션 기법 사용해서 풀었습니다.
저번주에 알고리즘 스터디에서 한건데 ㅋㅋ 금붕어가 따로 없네요.

[PGM] 멀리뛰기 / level2 / 못품

---

연속 부분 수열 합의 개수.js

[PGM] 연속 부분 수열 합의 개수 / LEVEL2 / 못품
